"""Initial migration with 2FA support

Revision ID: 5730dcb1e794
Revises: 
Create Date: 2025-12-30 04:30:33.375527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5730dcb1e794'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('two_factor_method', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('otp_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('otp_expiry')
        batch_op.drop_column('otp_code')
        batch_op.drop_column('two_factor_method')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
